version: '3'

services:
  extension:
    image: node:lts
    volumes:
      - ./:/app
    working_dir: /app
    command: 'bash -c "npm install && npm run watch"'
  webview:
    image: node:18.10
    volumes:
      - ./:/app
    working_dir: /app/web
    command: 'bash -c "npm install && npm run watch"'
